---
title: "25 faces"
author: "Rama"
date: "2022-07-21"
output: html_document
---
#This is the analysis for the NW-W condition (1st pilot version).
#Install necessary packages:
```{r setup, include=FALSE}
install.packages("tidyverse")
library(tidyverse)
library(jsonlite)
```
```{r data_loading}
library(jsonlite)
library(dplyr)
library(tidyverse)
library(ggplot2)  
library(ggforce)
library(sjPlot)
library(lme4)
library(lmerTest)
library(interactions)
library(ggpubr)
library(texreg)
library(reghelper)
```
```{r loading_data} 
setwd("pilot1")
##### uploading every json file and creating one big file #####
#unable to upload more than 100 files to git 
#pls download "pilot1" from slack 

#read all the files with jason ending
filenames <- list.files(pattern="*.json", recursive = T)

files <- lapply (filenames, fromJSON)
isCompleted <- lapply(files, nrow)
# we have 12 trials in total
completedData <- files[isCompleted == 12 ]
# every trial is in all_data combined
all_data <- do.call("bind_rows", completedData)
raw_data <- all_data
unique(raw_data$trial_type)
```
```{R}
#data transformation as the data from different variables look different - goal: to combine them in the end

# trial index 0 = attention check
atten_trial <- 0
atten_data <- raw_data[raw_data$trial_index == atten_trial, ]
atten_data <- atten_data %>% unnest(response)
names(atten_data)[names(atten_data) == "response"] <- "attention_check"

# trial index 1 = prolific id 
prolific_trial <- 1
prolific_data <- raw_data[raw_data$trial_index == prolific_trial, ]
prolific_data <- prolific_data %>% unnest(response)
names(prolific_data)[names(prolific_data) == "response"] <- "prolific_id"

# trial index 2 = response to start the questionnaire
start_response_trial <- 2
start_response_data <- raw_data[raw_data$trial_index == start_response_trial, ]
start_response_data <- start_response_data %>% unnest(response)
names(start_response_data)[names(start_response_data) == "response"] <- "start_response"

#trial index 3,4,5,6,7 for the organizations 1-5
org_trials <- c(3,4,5, 6, 7)
org_data <- raw_data[raw_data$trial_index %in% org_trials, ]
org_data <- org_data %>% unnest(response)  
org_data <- org_data %>% pivot_wider(names_from = name, values_from = value)

#trial index 6 for the moderator SDO 
moderator_trials <- c(8)
mod_data <- raw_data[raw_data$trial_index %in% moderator_trials, ]
mod_data <- mod_data %>% unnest(response) 
mod_data <- mod_data %>% pivot_wider(names_from = name, values_from = value)

#trial index 9 for the demographics
demographics_trials <- c(9)
demo_data <- raw_data[raw_data$trial_index %in% demographics_trials, ]
demo_data <- demo_data %>% unnest(response)
demo_data_wo_ethnic <- demo_data[demo_data$name != "ethnic[]", ]  %>% pivot_wider(names_from = name, values_from = value)
demo_data_ethnic <- demo_data[demo_data$name == "ethnic[]", ]
demo_data_ethnic <- demo_data_ethnic %>% nest(ethnic = c( value))
demo_data <- inner_join(demo_data_ethnic[, c("rt", "subject", "ethnic")], demo_data_wo_ethnic, by="subject")
  
# trial index 10 for feedback 
followup_trials <- c(10)
followup_data <- raw_data[raw_data$trial_index %in% followup_trials, ]
followup_data <- followup_data %>% unnest(response)
names(followup_data)[names(followup_data) == "response"] <- "followup_response"

```
```{r join_individual_data}
#join all the data trial from above into one 
demo_cols <- c("ethnic", "age", "children", "economic", "edu", "employment", "gender", "gender_description", "income", "ladder", "marital", "social")
df <- inner_join(org_data, mod_data[, c("rt", "subject", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "B1", "B2", "B3", "B4", "B5", "B6")], by = "subject") 
df <- inner_join(df, demo_data[, c("subject", demo_cols)], by = "subject") 
df <- inner_join(df, followup_data[, c("subject", "followup_response")], by = "subject") 
df <- inner_join(df, atten_data[, c("subject", "attention_check")], by = "subject")
df <- inner_join(df, start_response_data[, c("subject", "start_response")], by = "subject")

```
```{r}

#finding out lists in df 
sapply(df,class)

#unlist df to work with it
preprocessed_data <- apply(df,2,as.character)

#create csv document form json
x = write.csv(preprocessed_data, "/Users/ramat/Desktop/preprocessed_data_final.csv")

```
```{R}
#cleaning up the environment (not necessary step)
remove(mod_data,org_data, prolific_data,raw_data,start_response_data,all_data, atten_data,completedData,demo_data, demo_data_ethnic, demo_data_wo_ethnic, files, followup_data, isCompleted)
```
```{R}
############################Cleaning the excel################################# 
#Set working directory  
setwd("/Users/ramat/Desktop/")

#load full csv data (preprocessed data)
pd <- read.csv("/Users/ramat/Desktop/preprocessed_data_final.csv")

#Dropping those participants who failed the attention checks
#TRIAL INDEX 0
pd$attention_check[pd$attention_check=="r"] <- 1
pd$attention_check[pd$attention_check=="R"] <- 1
#Checking for failed attention checks
pd$attention_check[pd$attention_check!=1] 
#setting them to 0
pd$attention_check[pd$attention_check!=1] <- 0
pd$attention_check[is.na(pd$attention_check)==T] <- 0
#only put 1 into new subset
pd1 <- subset(pd, attention_check == 1)

#only considering participants who started the questionnaire 
#TRIAL INDEX 2
pd1$start_response[pd1$start_response==0] <- 1
pd1$start_response[is.na(pd1$start_response)==T] <- 0
pd1 <- subset(pd1, start_response == 1)


#during cleaning some rows were more than one time - to remove them first
#Checking for the same rows
pd1[47,]==pd1[48,]
pd2=pd1
#cleaning out the rows and duplicated data
pd1<-distinct(pd2[,2:56])
#duplicated(pd1[,2:56])

```
```{R}
################################Renaming variables#############################

#TRIAL INDEX 3-7
#1.DV - Fairness
names(pd1)[names(pd1) == "perception1"] <- "fairness"
#correcting errors in Yes and NO field
pd1$fairness[pd1$fairness=="c(\"N\", \"N\")"] <- "N"
pd1$fairness[pd1$fairness=="c(\"Y\", \"Y\")"] <- "Y"
#changing into 0 and 1
pd1$fairness[pd1$fairness == "Y"] <- 0
pd1$fairness[pd1$fairness == "N"] <- 1

#2.DV - Team work
names(pd1)[names(pd1) == "perception2"] <- "team_work"
#correcting errors in Yes and NO field
pd1$team_work[pd1$team_work=="c(\"N\", \"N\")"] <- "N"
pd1$team_work[pd1$team_work=="c(\"Y\", \"Y\")"] <- "Y"
#checking if the fields look correct
pd1$team_work
#changing into 0 and 1
pd1$teamwork[pd1$team_work == "Y"] <- 0
pd1$teamwork[pd1$team_work == "N"] <- 1

#3.DV - Work in teams
names(pd1)[names(pd1) == "perception3"] <- "work_in_team"
#correcting errors in Yes and NO field
pd1$work_in_team[pd1$work_in_team=="c(\"N\", \"N\")"] <- "N"
pd1$work_in_team[pd1$work_in_team=="c(\"Y\", \"Y\")"] <- "Y"
#checking if the fields look correct
pd1$work_in_team
#changing into 0 and 1
pd1$workinteam[pd1$work_in_team == "Y"] <- 0
pd1$workinteam[pd1$work_in_team == "N"] <- 1

#4.DV - personal interest to work in team
names(pd1)[names(pd1) == "perception4"] <- "distrust"
#correcting errors in Yes and NO field
pd1$distrust[pd1$distrust=="c(\"N\", \"N\")"] <- "N"
pd1$distrust[pd1$distrust=="c(\"Y\", \"Y\")"] <- "Y"
#checking if the fields look correct
pd1$distrust
#changing into 0 and 1
pd1$distrust[pd1$distrust == "Y"] <- 0
pd1$distrust[pd1$distrust == "N"] <- 1


#Trial Index 8 - Moderators
#5a.SDO - scale - just the RENAMING!
names(pd1)[names(pd1) == "A1"] <- "s1_earn_reward"
#correcting errors in field
pd1$s1_earn_reward[pd1$s1_earn_reward=="c(\"1\", \"1\")"] <- "1"
pd1$s1_earn_reward[pd1$s1_earn_reward=="c(\"2\", \"2\")"] <- "2"
pd1$s1_earn_reward[pd1$s1_earn_reward=="c(\"3\", \"3\")"] <- "3"
pd1$s1_earn_reward[pd1$s1_earn_reward=="c(\"4\", \"4\")"] <- "4"
pd1$s1_earn_reward[pd1$s1_earn_reward=="c(\"5\", \"5\")"] <- "5"
pd1$s1_earn_reward[pd1$s1_earn_reward=="c(\"6\", \"6\")"] <- "6"
pd1$s1_earn_reward[pd1$s1_earn_reward=="c(\"7\", \"7\")"] <- "7"
#checking if the fields look correct
pd1$s1_earn_reward


names(pd1)[names(pd1) == "A2"] <- "s2_inferior"
#correcting errors in field
pd1$s2_inferior[pd1$s2_inferior=="c(\"1\", \"1\")"] <- "1"
pd1$s2_inferior[pd1$s2_inferior=="c(\"2\", \"2\")"] <- "2"
pd1$s2_inferior[pd1$s2_inferior=="c(\"3\", \"3\")"] <- "3"
pd1$s2_inferior[pd1$s2_inferior=="c(\"4\", \"4\")"] <- "4"
pd1$s2_inferior[pd1$s2_inferior=="c(\"5\", \"5\")"] <- "5"
pd1$s2_inferior[pd1$s2_inferior=="c(\"6\", \"6\")"] <- "6"
pd1$s2_inferior[pd1$s2_inferior=="c(\"7\", \"7\")"] <- "7"
#checking if the fields look correct
pd1$s1_earn_reward

names(pd1)[names(pd1) == "A3"] <- "s3_group_dominate"
#correcting errors in field
pd1$s3_group_dominate[pd1$s3_group_dominate=="c(\"1\", \"1\")"] <- "1"
pd1$s3_group_dominate[pd1$s3_group_dominate=="c(\"2\", \"2\")"] <- "2"
pd1$s3_group_dominate[pd1$s3_group_dominate=="c(\"3\", \"3\")"] <- "3"
pd1$s3_group_dominate[pd1$s3_group_dominate=="c(\"4\", \"4\")"] <- "4"
pd1$s3_group_dominate[pd1$s3_group_dominate=="c(\"5\", \"5\")"] <- "5"
pd1$s3_group_dominate[pd1$s3_group_dominate=="c(\"6\", \"6\")"] <- "6"
pd1$s3_group_dominate[pd1$s3_group_dominate=="c(\"7\", \"7\")"] <- "7"
#checking if the fields look correct
pd1$s3_group_dominate


names(pd1)[names(pd1) == "A4"] <- "s4_bottom_deserve"
#correcting errors in 1 and 5 field
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve=="c(\"1\", \"1\")"] <- "1"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve=="c(\"2\", \"2\")"] <- "2"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve=="c(\"3\", \"3\")"] <- "3"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve=="c(\"4\", \"4\")"] <- "4"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve=="c(\"5\", \"5\")"] <- "5"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve=="c(\"6\", \"6\")"] <- "6"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve=="c(\"7\", \"7\")"] <- "7"
#checking if the fields look correct
pd1$s4_bottom_deserve

names(pd1)[names(pd1) == "A5"] <- "s5_group_equality"
#correcting errors in 1 and 5 field
pd1$s5_group_equality[pd1$s5_group_equality=="c(\"1\", \"1\")"] <- "1"
pd1$s5_group_equality[pd1$s5_group_equality=="c(\"2\", \"2\")"] <- "2"
pd1$s5_group_equality[pd1$s5_group_equality=="c(\"3\", \"3\")"] <- "3"
pd1$s5_group_equality[pd1$s5_group_equality=="c(\"4\", \"4\")"] <- "4"
pd1$s5_group_equality[pd1$s5_group_equality=="c(\"5\", \"5\")"] <- "5"
pd1$s5_group_equality[pd1$s5_group_equality=="c(\"6\", \"6\")"] <- "6"
pd1$s5_group_equality[pd1$s5_group_equality=="c(\"7\", \"7\")"] <- "7"
#checking if the fields look correct
pd1$s5_group_equality

names(pd1)[names(pd1) == "A6"] <- "s6_group_equal_unjust"
#correcting errors in 1 and 5 field
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust=="c(\"1\", \"1\")"] <- "1"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust=="c(\"2\", \"2\")"] <- "2"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust=="c(\"3\", \"3\")"] <- "3"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust=="c(\"4\", \"4\")"] <- "4"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust=="c(\"5\", \"5\")"] <- "5"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust=="c(\"6\", \"6\")"] <- "6"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust=="c(\"7\", \"7\")"] <- "7"
#checking if the fields look correct
pd1$s6_group_equal_unjust

names(pd1)[names(pd1) == "A7"] <- "s7_act_equalize"
#correcting errors in 1 and 5 field
pd1$s7_act_equalize[pd1$s7_act_equalize=="c(\"1\", \"1\")"] <- "1"
pd1$s7_act_equalize[pd1$s7_act_equalize=="c(\"2\", \"2\")"] <- "2"
pd1$s7_act_equalize[pd1$s7_act_equalize=="c(\"3\", \"3\")"] <- "3"
pd1$s7_act_equalize[pd1$s7_act_equalize=="c(\"4\", \"4\")"] <- "4"
pd1$s7_act_equalize[pd1$s7_act_equalize=="c(\"5\", \"5\")"] <- "5"
pd1$s7_act_equalize[pd1$s7_act_equalize=="c(\"6\", \"6\")"] <- "6"
pd1$s7_act_equalize[pd1$s7_act_equalize=="c(\"7\", \"7\")"] <- "7"
#checking if the fields look correct
pd1$s7_act_equalize

names(pd1)[names(pd1) == "A8"] <- "s8_succeed_equal"
#correcting errors in 1 and 5 field
pd1$s8_succeed_equal[pd1$s8_succeed_equal=="c(\"1\", \"1\")"] <- "1"
pd1$s8_succeed_equal[pd1$s8_succeed_equal=="c(\"2\", \"2\")"] <- "2"
pd1$s8_succeed_equal[pd1$s8_succeed_equal=="c(\"3\", \"3\")"] <- "3"
pd1$s8_succeed_equal[pd1$s8_succeed_equal=="c(\"4\", \"4\")"] <- "4"
pd1$s8_succeed_equal[pd1$s8_succeed_equal=="c(\"5\", \"5\")"] <- "5"
pd1$s8_succeed_equal[pd1$s8_succeed_equal=="c(\"6\", \"6\")"] <- "6"
pd1$s8_succeed_equal[pd1$s8_succeed_equal=="c(\"7\", \"7\")"] <- "7"
#checking if the fields look correct

#5b.Belief in Just world scale
names(pd1)[names(pd1) == "B1"] <- "b1_just_world"
pd1$b1_just_world[pd1$b1_just_world=="c(\"1\", \"1\")"] <- "1"
pd1$b1_just_world[pd1$b1_just_world=="c(\"2\", \"2\")"] <- "2"
pd1$b1_just_world[pd1$b1_just_world=="c(\"3\", \"3\")"] <- "3"
pd1$b1_just_world[pd1$b1_just_world=="c(\"4\", \"4\")"] <- "4"
pd1$b1_just_world[pd1$b1_just_world=="c(\"5\", \"5\")"] <- "5"
pd1$b1_just_world[pd1$b1_just_world=="c(\"6\", \"6\")"] <- "6"


names(pd1)[names(pd1) == "B2"] <- "b2_people_deserve"
pd1$b2_people_deserve[pd1$b2_people_deserve=="c(\"1\", \"1\")"] <- "1"
pd1$b2_people_deserve[pd1$b2_people_deserve=="c(\"2\", \"2\")"] <- "2"
pd1$b2_people_deserve[pd1$b2_people_deserve=="c(\"3\", \"3\")"] <- "3"
pd1$b2_people_deserve[pd1$b2_people_deserve=="c(\"4\", \"4\")"] <- "4"
pd1$b2_people_deserve[pd1$b2_people_deserve=="c(\"5\", \"5\")"] <- "5"
pd1$b2_people_deserve[pd1$b2_people_deserve=="c(\"6\", \"6\")"] <- "6"


names(pd1)[names(pd1) == "B3"] <- "b3_confident_justice"
pd1$b3_confident_justice[pd1$b3_confident_justice=="c(\"1\", \"1\")"] <- "1"
pd1$b3_confident_justice[pd1$b3_confident_justice=="c(\"2\", \"2\")"] <- "2"
pd1$b3_confident_justice[pd1$b3_confident_justice=="c(\"3\", \"3\")"] <- "3"
pd1$b3_confident_justice[pd1$b3_confident_justice=="c(\"4\", \"4\")"] <- "4"
pd1$b3_confident_justice[pd1$b3_confident_justice=="c(\"5\", \"5\")"] <- "5"
pd1$b3_confident_justice[pd1$b3_confident_justice=="c(\"6\", \"6\")"] <- "6"


names(pd1)[names(pd1) == "B4"] <- "b4_compensate_injustice"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice=="c(\"1\", \"1\")"] <- "1"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice=="c(\"2\", \"2\")"] <- "2"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice=="c(\"3\", \"3\")"] <- "3"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice=="c(\"4\", \"4\")"] <- "4"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice=="c(\"5\", \"5\")"] <- "5"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice=="c(\"6\", \"6\")"] <- "6"


names(pd1)[names(pd1) == "B5"] <- "b5_injust_exeception"
pd1$b5_injust_exeception[pd1$b5_injust_exeception=="c(\"1\", \"1\")"] <- "1"
pd1$b5_injust_exeception[pd1$b5_injust_exeception=="c(\"2\", \"2\")"] <- "2"
pd1$b5_injust_exeception[pd1$b5_injust_exeception=="c(\"3\", \"3\")"] <- "3"
pd1$b5_injust_exeception[pd1$b5_injust_exeception=="c(\"4\", \"4\")"] <- "4"
pd1$b5_injust_exeception[pd1$b5_injust_exeception=="c(\"5\", \"5\")"] <- "5"
pd1$b5_injust_exeception[pd1$b5_injust_exeception=="c(\"6\", \"6\")"] <- "6"


names(pd1)[names(pd1) == "B6"] <- "b6_fair_decision"
pd1$b6_fair_decision[pd1$b6_fair_decision=="c(\"1\", \"1\")"] <- "1"
pd1$b6_fair_decision[pd1$b6_fair_decision=="c(\"2\", \"2\")"] <- "2"
pd1$b6_fair_decision[pd1$b6_fair_decision=="c(\"3\", \"3\")"] <- "3"
pd1$b6_fair_decision[pd1$b6_fair_decision=="c(\"4\", \"4\")"] <- "4"
pd1$b6_fair_decision[pd1$b6_fair_decision=="c(\"5\", \"5\")"] <- "5"
pd1$b6_fair_decision[pd1$b6_fair_decision=="c(\"6\", \"6\")"] <- "6"


#ethnic
pd1$ethnic[pd1$ethnic=="list(value = \"Asian\")"] <- "Asian"
pd1$ethnic[pd1$ethnic=="list(value = c(\"Asian\", \"Asian\"))"] <- "Asian"
pd1$ethnic[pd1$ethnic=="list(value = \"White\")"] <- "White"
pd1$ethnic[pd1$ethnic=="list(value = c(\"White\", \"White\"))"] <- "White"
pd1$ethnic[pd1$ethnic=="list(value = \"Black-AfrAmr\")"] <- "Black-AfrAmr"
pd1$ethnic[pd1$ethnic=="list(value = \"Other\")" ] <- "Other"

#age
pd1$age[pd1$age=="c(\"19\", \"19\")"] <- "19"
pd1$age[pd1$age=="c(\"29\", \"29\")"] <- "29"
pd1$age[pd1$age=="c(\"31\", \"31\")"] <- "31"
pd1$age[pd1$age=="c(\"30\", \"30\")"] <- "30"

#children
pd1$children[pd1$children=="c(\"0\", \"0\")"] <- "0"
pd1$children[pd1$children=="c(\"2\", \"2\")"] <- "2"

#economic
pd1$economic[pd1$economic=="c(\"1\", \"1\")"] <- "1"
pd1$economic[pd1$economic=="c(\"2\", \"2\")"] <- "2"

#education
pd1$edu[pd1$edu=="c(\"4\", \"4\")"] <- "4"
pd1$edu[pd1$edu=="c(\"6\", \"6\")"] <- "6"
pd1$edu[pd1$edu=="c(\"5\", \"5\")"] <- "5"
pd1$edu[pd1$edu=="c(\"2\", \"2\")"] <- "2"

#employment
pd1$employment[pd1$employment=="c(\"1\", \"1\")"] <- "1"
pd1$employment[pd1$employment=="c(\"3\", \"3\")"] <- "3"

#gender
pd1$gender[pd1$gender=="c(\"f\", \"f\")"] <- "f"
pd1$gender[pd1$gender=="c(\"o\", \"o\")"] <- "o"

#gender description 
pd1$gender_description[pd1$gender_description=="c(\"Nonbinary\", \"Nonbinary\")"] <- "Nonbinary"

#income
pd1$income[pd1$income=="c(\"3\", \"3\")"] <- "3"
pd1$income[pd1$income=="c(\"6\", \"6\")"] <- "6"
pd1$income[pd1$income=="c(\"11\", \"11\")"] <- "11"
pd1$income[pd1$income=="c(\"4\", \"4\")"] <- "4"
pd1$income

#ladder
pd1$ladder[pd1$ladder=="c(\"4\", \"4\")"] <- "4"
pd1$ladder[pd1$ladder=="c(\"6\", \"6\")"] <- "6"
pd1$ladder[pd1$ladder=="c(\"5\", \"5\")"] <- "5"

#marital status 
pd1$marital[pd1$marital == 1] <- "Divorced"
pd1$marital[pd1$marital=="c(\"1\", \"1\")"] <- "Divorced"
pd1$marital[pd1$marital == 2] <- "Married"
pd1$marital[pd1$marital == 3] <- "Seperated"
pd1$marital[pd1$marital == 4] <- "Widowed"
pd1$marital[pd1$marital=="c(\"4\", \"4\")"] <- "Widowed"

#social
pd1$social[pd1$social=="c(\"2\", \"2\")"] <- "2"
pd1$social[pd1$social=="c(\"1\", \"1\")"] <- "1"

#2. edu status
pd1$edu[pd1$edu == 1] <- "Some high school or less"
pd1$edu[pd1$edu == 2] <- "Two year college degree"
pd1$edu[pd1$edu == 3] <- "Some college but no degree"
pd1$edu[pd1$edu == 4] <- "High school or GED"
pd1$edu[pd1$edu == 5] <- "Four year college degree"
pd1$edu[pd1$edu == 6] <- "Graduate degree"

#3. Employment
pd1$employment[pd1$employment == 1] <- "Full-time"
pd1$employment[pd1$employment == 2] <- " Part-time"
pd1$employment[pd1$employment == 3] <- "Prefer not to answer"
pd1$employment[pd1$employment == 4] <- "Unemployed"

#4. Income
pd1$income[pd1$income == 1] <- "$10,000 to $19,999 "
pd1$income[pd1$income == 2] <- "$100,000 to $124,999"
pd1$income[pd1$income == 3] <- "$125,000 to $149,999"
pd1$income[pd1$income == 4] <- "$150,000 to $199,999"
pd1$income[pd1$income == 5] <- "$20,000 to $29,999"
pd1$income[pd1$income == 6] <- "$200,000 or more"
pd1$income[pd1$income == 7] <- "$30,000 to $39,999"
pd1$income[pd1$income == 8] <- "$40,000 to $49,999"
pd1$income[pd1$income == 9] <- "$50,000 to $59,999"
pd1$income[pd1$income == 10] <- "$60,000 to $69,999"
pd1$income[pd1$income == 11] <- "$70,000 to $79,999"
pd1$income[pd1$income == 12] <- "$80,000 to $89,999"
pd1$income[pd1$income == 13] <- "$90,000 to $99,999"
pd1$income[pd1$income == 14] <- "Less than $10,000"

#5.Political orientation - social issues
pd1$economic[pd1$economic == 1] <- "Conservative"
pd1$economic[pd1$economic == 2] <- "Liberal"
pd1$economic[pd1$economic == 3] <- "Moderate"
pd1$economic[pd1$economic == 4] <- "Slightly conservative"
pd1$economic[pd1$economic == 5] <- "Slightly liberal"
pd1$economic[pd1$economic == 6] <- "Very conservative"
pd1$economic[pd1$economic == 7] <- "Very liberal"

#6.Political orientation - economic issues
pd1$social[pd1$social == 1] <- "Conservative"
pd1$social[pd1$social == 2] <- "Liberal"
pd1$social[pd1$social == 3] <- "Moderate"
pd1$social[pd1$social == 4] <- "Slightly conservative"
pd1$social[pd1$social == 5] <- "Slightly liberal"
pd1$social[pd1$social == 6] <- "Very conservative"
pd1$social[pd1$social == 7] <- "Very liberal"

#SDO scale
pd1$s1_earn_reward[pd1$s1_earn_reward == 1] <- "Strongly favor"
pd1$s1_earn_reward[pd1$s1_earn_reward == 2] <- "Somewhat favor"
pd1$s1_earn_reward[pd1$s1_earn_reward == 3] <- "Slightly favor"
pd1$s1_earn_reward[pd1$s1_earn_reward == 4] <- "Neutral"
pd1$s1_earn_reward[pd1$s1_earn_reward == 5] <- "Slightly oppose"
pd1$s1_earn_reward[pd1$s1_earn_reward == 6] <- "Somewhat oppose"
pd1$s1_earn_reward[pd1$s1_earn_reward == 7] <- "Strongly oppose"

pd1$s2_inferior[pd1$s2_inferior == 1] <- "Strongly favor"
pd1$s2_inferior[pd1$s2_inferior == 2] <- "Somewhat favor"
pd1$s2_inferior[pd1$s2_inferior == 3] <- "Slightly favor"
pd1$s2_inferior[pd1$s2_inferior == 4] <- "Neutral"
pd1$s2_inferior[pd1$s2_inferior == 5] <- "Slightly oppose"
pd1$s2_inferior[pd1$s2_inferior == 6] <- "Somewhat oppose"
pd1$s2_inferior[pd1$s2_inferior == 7] <- "Strongly oppose"

pd1$s3_group_dominate[pd1$s3_group_dominate == 1] <- "Strongly favor"
pd1$s3_group_dominate[pd1$s3_group_dominate == 2] <- "Somewhat favor"
pd1$s3_group_dominate[pd1$s3_group_dominate == 3] <- "Slightly favor"
pd1$s3_group_dominate[pd1$s3_group_dominate == 4] <- "Neutral"
pd1$s3_group_dominate[pd1$s3_group_dominate == 5] <- "Slightly oppose"
pd1$s3_group_dominate[pd1$s3_group_dominate == 6] <- "Somewhat oppose"
pd1$s3_group_dominate[pd1$s3_group_dominate == 7] <- "Strongly oppose"

pd1$s4_bottom_deserve[pd1$s4_bottom_deserve == 1] <- "Strongly favor"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve == 2] <- "Somewhat favor"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve == 3] <- "Slightly favor"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve == 4] <- "Neutral"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve == 5] <- "Slightly oppose"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve == 6] <- "Somewhat oppose"
pd1$s4_bottom_deserve[pd1$s4_bottom_deserve == 7] <- "Strongly oppose"


pd1$s5_group_equality[pd1$s5_group_equality == 1] <- "Strongly favor"
pd1$s5_group_equality[pd1$s5_group_equality == 2] <- "Somewhat favor"
pd1$s5_group_equality[pd1$s5_group_equality == 3] <- "Slightly favor"
pd1$s5_group_equality[pd1$s5_group_equality == 4] <- "Neutral"
pd1$s5_group_equality[pd1$s5_group_equality == 5] <- "Slightly oppose"
pd1$s5_group_equality[pd1$s5_group_equality == 6] <- "Somewhat oppose"
pd1$s5_group_equality[pd1$s5_group_equality == 7] <- "Strongly oppose"


pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust == 1] <- "Strongly favor"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust == 2] <- "Somewhat favor"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust == 3] <- "Slightly favor"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust == 4] <- "Neutral"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust == 5] <- "Slightly oppose"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust == 6] <- "Somewhat oppose"
pd1$s6_group_equal_unjust[pd1$s6_group_equal_unjust == 7] <- "Strongly oppose"


pd1$s7_act_equalize[pd1$s7_act_equalize == 1] <- "Strongly favor"
pd1$s7_act_equalize[pd1$s7_act_equalize == 2] <- "Somewhat favor"
pd1$s7_act_equalize[pd1$s7_act_equalize == 3] <- "Slightly favor"
pd1$s7_act_equalize[pd1$s7_act_equalize == 4] <- "Neutral"
pd1$s7_act_equalize[pd1$s7_act_equalize == 5] <- "Slightly oppose"
pd1$s7_act_equalize[pd1$s7_act_equalize == 6] <- "Somewhat oppose"
pd1$s7_act_equalize[pd1$s7_act_equalize == 7] <- "Strongly oppose"


pd1$s8_succeed_equal[pd1$s8_succeed_equal == 1] <- "Strongly favor"
pd1$s8_succeed_equal[pd1$s8_succeed_equal == 2] <- "Somewhat favor"
pd1$s8_succeed_equal[pd1$s8_succeed_equal == 3] <- "Slightly favor"
pd1$s8_succeed_equal[pd1$s8_succeed_equal == 4] <- "Neutral"
pd1$s8_succeed_equal[pd1$s8_succeed_equal == 5] <- "Slightly oppose"
pd1$s8_succeed_equal[pd1$s8_succeed_equal == 6] <- "Somewhat oppose"
pd1$s8_succeed_equal[pd1$s8_succeed_equal == 7] <- "Strongly oppose"


#9. Belief in just world
pd1$b1_just_world[pd1$b1_just_world == 1] <- "Strongly disagree"
pd1$b1_just_world[pd1$b1_just_world == 2] <- "Disagree"
pd1$b1_just_world[pd1$b1_just_world == 3] <- "Slightly disagree"
pd1$b1_just_world[pd1$b1_just_world == 4] <- "Slightly Agree"
pd1$b1_just_world[pd1$b1_just_world == 5] <- "Agree"
pd1$b1_just_world[pd1$b1_just_world == 6] <- "Strongly agree"


pd1$b2_people_deserve[pd1$b2_people_deserve == 1] <- "Strongly disagree"
pd1$b2_people_deserve[pd1$b2_people_deserve == 2] <- "Disagree"
pd1$b2_people_deserve[pd1$b2_people_deserve == 3] <- "Slightly disagree"
pd1$b2_people_deserve[pd1$b2_people_deserve == 4] <- "Slightly Agree"
pd1$b2_people_deserve[pd1$b2_people_deserve == 5] <- "Agree"
pd1$b2_people_deserve[pd1$b2_people_deserve == 6] <- "Strongly agree"



pd1$b3_confident_justice[pd1$b3_confident_justice == 1] <- "Strongly disagree"
pd1$b3_confident_justice[pd1$b3_confident_justice == 2] <- "Disagree"
pd1$b3_confident_justice[pd1$b3_confident_justice == 3] <- "Slightly disagree"
pd1$b3_confident_justice[pd1$b3_confident_justice == 4] <- "Slightly Agree"
pd1$b3_confident_justice[pd1$b3_confident_justice == 5] <- "Agree"
pd1$b3_confident_justice[pd1$b3_confident_justice == 6] <- "Strongly agree"



pd1$b4_compensate_injustice[pd1$b4_compensate_injustice == 1] <- "Strongly disagree"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice == 2] <- "Disagree"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice == 3] <- "Slightly disagree"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice == 4] <- "Slightly Agree"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice == 5] <- "Agree"
pd1$b4_compensate_injustice[pd1$b4_compensate_injustice == 6] <- "Strongly agree"



pd1$b5_injust_exeception[pd1$b5_injust_exeception == 1] <- "Strongly disagree"
pd1$b5_injust_exeception[pd1$b5_injust_exeception == 2] <- "Disagree"
pd1$b5_injust_exeception[pd1$b5_injust_exeception == 3] <- "Slightly disagree"
pd1$b5_injust_exeception[pd1$b5_injust_exeception == 4] <- "Slightly Agree"
pd1$b5_injust_exeception[pd1$b5_injust_exeception == 5] <- "Agree"
pd1$b5_injust_exeception[pd1$b5_injust_exeception == 6] <- "Strongly agree"


pd1$b6_fair_decision[pd1$b6_fair_decision == 1] <- "Strongly disagree"
pd1$b6_fair_decision[pd1$b6_fair_decision == 2] <- "Disagree"
pd1$b6_fair_decision[pd1$b6_fair_decision == 3] <- "Slightly disagree"
pd1$b6_fair_decision[pd1$b6_fair_decision == 4] <- "Slightly Agree"
pd1$b6_fair_decision[pd1$b6_fair_decision == 5] <- "Agree"
pd1$b6_fair_decision[pd1$b6_fair_decision == 6] <- "Strongly agree"


#comments from people
#I think I was supposed to consider the race and gender of these people, but not knowing anything about their jobs or their performance, it would have been prejudice for me to assume pay was unfair either way.
#It was interesting that none of the employees appeared to be over age 30 or so.
#For some of the questions, it might be best to split them into separate pages (such as four questions per page).  The questions/answers were spread too far across the page and were bunched together, which made it harder to read.

#Writing the data into csv file
x = write.csv(pd1, "/Users/ramat/Desktop/cleaned.csv")
```
```{R}
setwd("/Users/ramat/Desktop/")

#load full csv data (preprocessed data)
cd <- read.csv("/Users/ramat/Desktop/cleaned.csv")
#recode to do analysis

cd$fairness[cd$fairness == "Y"] <- 0
cd$fairness[cd$fairness == "N"] <- 1

cd$team_work[cd$team_work == "Y"] <- 0
cd$team_work[cd$team_work == "N"] <- 1

cd$work_in_team[cd$work_in_team == "Y"] <- 0
cd$work_in_team[cd$work_in_team == "N"] <- 1

cd$distrust[cd$work_in_team == "Y"] <- 0
cd$distrust[cd$work_in_team == "N"] <- 1

cd$social[cd$social == "Very liberal"] <- 1
cd$social[cd$social == "Liberal"] <- 2
cd$social[cd$social == "Slightly liberal"] <- 3
cd$social[cd$social == "Moderate"] <- 4
cd$social[cd$social == "Slightly conservative"] <- 5
cd$social[cd$social == "Conservative"] <- 6
cd$social[cd$social == "Very conservative"] <- 7

cd$economic[cd$economic == "Very liberal"] <- 1
cd$economic[cd$economic == "Liberal"] <- 2
cd$economic[cd$economic == "Slightly liberal"] <- 3
cd$economic[cd$economic == "Moderate"] <- 4
cd$economic[cd$economic == "Slightly conservative"] <- 5
cd$economic[cd$economic == "Conservative"] <- 6
cd$economic[cd$economic == "Very conservative"] <- 7

class(cd$social)
class(cd$economic)
cd$PoliticalOrientation <- ((as.numeric(cd$social))+(as.numeric(cd$economic)))/2
  
cd$s1_earn_reward[cd$s1_earn_reward == "Strongly oppose"] <- 1
cd$s1_earn_reward[cd$s1_earn_reward == "Somewhat oppose"] <- 2
cd$s1_earn_reward[cd$s1_earn_reward == "Slightly oppose"] <- 3
cd$s1_earn_reward[cd$s1_earn_reward == "Neutral"] <- 4
cd$s1_earn_reward[cd$s1_earn_reward == "Slightly favor"] <- 5
cd$s1_earn_reward[cd$s1_earn_reward == "Somewhat favor"] <- 6
cd$s1_earn_reward[cd$s1_earn_reward == "Strongly favor"] <- 7

cd$s2_inferior[cd$s2_inferior == "Strongly oppose"] <- 1
cd$s2_inferior[cd$s2_inferior == "Somewhat oppose"] <- 2
cd$s2_inferior[cd$s2_inferior == "Slightly oppose"] <- 3
cd$s2_inferior[cd$s2_inferior == "Neutral"] <- 4
cd$s2_inferior[cd$s2_inferior == "Slightly favor"] <- 5
cd$s2_inferior[cd$s2_inferior == "Somewhat favor"] <- 6
cd$s2_inferior[cd$s2_inferior == "Strongly favor"] <- 7

cd$s3_group_dominate[cd$s3_group_dominate == "Strongly oppose"] <- 7
cd$s3_group_dominate[cd$s3_group_dominate == "Somewhat oppose"] <- 6
cd$s3_group_dominate[cd$s3_group_dominate == "Slightly oppose"] <- 5
cd$s3_group_dominate[cd$s3_group_dominate == "Neutral"] <- 4
cd$s3_group_dominate[cd$s3_group_dominate == "Slightly favor"] <- 3
cd$s3_group_dominate[cd$s3_group_dominate == "Somewhat favor"] <- 2
cd$s3_group_dominate[cd$s3_group_dominate == "Strongly favor"] <- 1

cd$s4_bottom_deserve[cd$s4_bottom_deserve == "Strongly oppose"] <- 7
cd$s4_bottom_deserve[cd$s4_bottom_deserve == "Somewhat oppose"] <- 6
cd$s4_bottom_deserve[cd$s4_bottom_deserve == "Slightly oppose"] <- 5
cd$s4_bottom_deserve[cd$s4_bottom_deserve == "Neutral"] <- 4
cd$s4_bottom_deserve[cd$s4_bottom_deserve == "Slightly favor"] <- 3
cd$s4_bottom_deserve[cd$s4_bottom_deserve == "Somewhat favor"] <- 2
cd$s4_bottom_deserve[cd$s4_bottom_deserve == "Strongly favor"] <- 1

cd$s5_group_equality[cd$s5_group_equality == "Strongly oppose"] <- 1
cd$s5_group_equality[cd$s5_group_equality == "Somewhat oppose"] <- 2
cd$s5_group_equality[cd$s5_group_equality == "Slightly oppose"] <- 3
cd$s5_group_equality[cd$s5_group_equality == "Neutral"] <- 4
cd$s5_group_equality[cd$s5_group_equality == "Slightly favor"] <- 5
cd$s5_group_equality[cd$s5_group_equality == "Somewhat favor"] <- 6
cd$s5_group_equality[cd$s5_group_equality == "Strongly favor"] <- 7

cd$s6_group_equal_unjust[cd$s6_group_equal_unjust == "Strongly oppose"] <- 1
cd$s6_group_equal_unjust[cd$s6_group_equal_unjust == "Somewhat oppose"] <- 2
cd$s6_group_equal_unjust[cd$s6_group_equal_unjust == "Slightly oppose"] <- 3
cd$s6_group_equal_unjust[cd$s6_group_equal_unjust == "Neutral"] <- 4
cd$s6_group_equal_unjust[cd$s6_group_equal_unjust == "Slightly favor"] <- 5
cd$s6_group_equal_unjust[cd$s6_group_equal_unjust == "Somewhat favor"] <- 6
cd$s6_group_equal_unjust[cd$s6_group_equal_unjust == "Strongly favor"] <- 7

cd$s7_act_equalize[cd$s7_act_equalize == "Strongly oppose"] <- 7
cd$s7_act_equalize[cd$s7_act_equalize == "Somewhat oppose"] <- 6
cd$s7_act_equalize[cd$s7_act_equalize == "Slightly oppose"] <- 5
cd$s7_act_equalize[cd$s7_act_equalize == "Neutral"] <- 4
cd$s7_act_equalize[cd$s7_act_equalize == "Slightly favor"] <- 3
cd$s7_act_equalize[cd$s7_act_equalize == "Somewhat favor"] <- 2
cd$s7_act_equalize[cd$s7_act_equalize == "Strongly favor"] <- 1

cd$s8_succeed_equal[cd$s8_succeed_equal == "Strongly oppose"] <- 7
cd$s8_succeed_equal[cd$s8_succeed_equal == "Somewhat oppose"] <- 6
cd$s8_succeed_equal[cd$s8_succeed_equal == "Slightly oppose"] <- 5
cd$s8_succeed_equal[cd$s8_succeed_equal == "Neutral"] <- 4
cd$s8_succeed_equal[cd$s8_succeed_equal == "Slightly favor"] <- 3
cd$s8_succeed_equal[cd$s8_succeed_equal == "Somewhat favor"] <- 2
cd$s8_succeed_equal[cd$s8_succeed_equal == "Strongly favor"] <- 1

cd$SDO <- (((as.numeric(cd$s1_earn_reward))+(as.numeric(cd$s2_inferior))+(as.numeric(cd$s3_group_dominate))+(as.numeric(cd$s4_bottom_deserve))+(as.numeric(cd$s5_group_equality))+(as.numeric(cd$s6_group_equal_unjust))+(as.numeric(cd$s7_act_equalize))+(as.numeric(cd$s8_succeed_equal))))/8

#recode further variables - belief in just world
cd$b1_just_world[cd$b1_just_world == "Strongly disagree"] <- 1
cd$b1_just_world[cd$b1_just_world == "Disagree"] <- 2
cd$b1_just_world[cd$b1_just_world == "Slightly disagree"] <- 3
cd$b1_just_world[cd$b1_just_world == "Slightly Agree"] <- 4
cd$b1_just_world[cd$b1_just_world == "Agree"] <- 5
cd$b1_just_world[cd$b1_just_world == "Strongly agree"] <- 6

cd$b2_people_deserve[cd$b2_people_deserve == "Strongly disagree"] <- 1
cd$b2_people_deserve[cd$b2_people_deserve == "Disagree"] <- 2
cd$b2_people_deserve[cd$b2_people_deserve == "Slightly disagree"] <- 3
cd$b2_people_deserve[cd$b2_people_deserve == "Slightly Agree"] <- 4
cd$b2_people_deserve[cd$b2_people_deserve == "Agree"] <- 5
cd$b2_people_deserve[cd$b2_people_deserve == "Strongly agree"] <- 6

cd$b3_confident_justice[cd$b3_confident_justice == "Strongly disagree"] <- 1
cd$b3_confident_justice[cd$b3_confident_justice == "Disagree"] <- 2
cd$b3_confident_justice[cd$b3_confident_justice == "Slightly disagree"] <- 3
cd$b3_confident_justice[cd$b3_confident_justice == "Slightly Agree"] <- 4
cd$b3_confident_justice[cd$b3_confident_justice == "Agree"] <- 5
cd$b3_confident_justice[cd$b3_confident_justice == "Strongly agree"] <- 6

cd$b4_compensate_injustice[cd$b4_compensate_injustice == "Strongly disagree"] <- 1
cd$b4_compensate_injustice[cd$b4_compensate_injustice == "Disagree"] <- 2
cd$b4_compensate_injustice[cd$b4_compensate_injustice == "Slightly disagree"] <- 3
cd$b4_compensate_injustice[cd$b4_compensate_injustice == "Slightly Agree"] <- 4
cd$b4_compensate_injustice[cd$b4_compensate_injustice == "Agree"] <- 5
cd$b4_compensate_injustice[cd$b4_compensate_injustice == "Strongly agree"] <- 6

cd$b5_injust_exeception[cd$b5_injust_exeception == "Strongly disagree"] <- 1
cd$b5_injust_exeception[cd$b5_injust_exeception == "Disagree"] <- 2
cd$b5_injust_exeception[cd$b5_injust_exeception == "Slightly disagree"] <- 3
cd$b5_injust_exeception[cd$b5_injust_exeception == "Slightly Agree"] <- 4
cd$b5_injust_exeception[cd$b5_injust_exeception == "Agree"] <- 5
cd$b5_injust_exeception[cd$b5_injust_exeception == "Strongly agree"] <- 6

cd$b6_fair_decision[cd$b6_fair_decision == "Strongly disagree"] <- 1
cd$b6_fair_decision[cd$b6_fair_decision == "Disagree"] <- 2
cd$b6_fair_decision[cd$b6_fair_decision == "Slightly disagree"] <- 3
cd$b6_fair_decision[cd$b6_fair_decision == "Slightly Agree"] <- 4
cd$b6_fair_decision[cd$b6_fair_decision == "Agree"] <- 5
cd$b6_fair_decision[cd$b6_fair_decision == "Strongly agree"] <- 6

cd$BJW <- ((as.numeric(cd$b1_just_world)) + (as.numeric(cd$b2_people_deserve))+ (as.numeric(cd$b3_confident_justice)) + (as.numeric(cd$b4_compensate_injustice))  + (as.numeric(cd$b5_injust_exeception)) + (as.numeric(cd$b6_fair_decision)))/6

#gender
cd$gender[cd$gender == "m"] <- 0
cd$gender[cd$gender == "f"] <- 1
cd$gender[cd$gender == "0"] <- 1

#ethic
cd$ethnic[cd$ethnic == "White"] <- 0
cd$ethnic[cd$ethnic == "Asian"] <- 1
cd$ethnic[cd$ethnic == "Other"] <- 1
cd$ethnic[cd$ethnic=="Black-AfrAmr"] <- 1
cd$ethnic[cd$ethnic =="list(value = c(\"White\", \"Black-AfrAmr\"))"] <- 1
cd$ethnic[cd$ethnic =="list(value = c(\"White\", \"Black-AfrAmr\", \"AI-AN\"))"] <- 1
cd$ethnic[cd$ethnic=="list(value = c(\"White\", \"AI-AN\"))"] <- 1
cd$ethnic[cd$ethnic=="list(value = c(\"White\", \"NH-PI\", \"AI-AN\"))"] <- 1
cd$ethnic[cd$ethnic=="list(value = c(\"Asian\", \"Black-AfrAmr\"))"] <- 1
cd$ethnic[cd$ethnic=="list(value = c(\"White\", \"Asian\"))" ] <- 1

#income
cd$income[cd$income == "Less than $10,000"] <- 10000
cd$income[cd$income == "$10,000 to $19,999 "] <- 15000
cd$income[cd$income == "$20,000 to $29,999"] <- 25000
cd$income[cd$income == "$30,000 to $39,999"] <- 35000
cd$income[cd$income == "$40,000 to $49,999"] <- 45000
cd$income[cd$income == "$50,000 to $59,999"] <- 55000
cd$income[cd$income == "$60,000 to $69,999"] <- 65000
cd$income[cd$income == "$70,000 to $79,999"] <- 75000
cd$income[cd$income == "$80,000 to $89,999"] <- 85000
cd$income[cd$income == "$90,000 to $99,999"] <- 95000
cd$income[cd$income == "$100,000 to $124,999"] <- 112500
cd$income[cd$income == "$125,000 to $149,999"] <- 137500
cd$income[cd$income == "$150,000 to $199,999"] <- 175000
cd$income[cd$income == "$200,000 or more"] <- 225000

cd$income_log <- log(as.numeric(cd$income))

#education
cd$edu[cd$edu == "Some high school or less"] <- 1
cd$edu[cd$edu == "Two year college degree"] <- 2
cd$edu[cd$edu == "Some college but no degree"] <- 3
cd$edu[cd$edu == "High school or GED"] <- 4
cd$edu[cd$edu == "Four year college degree"] <- 5
cd$edu[cd$edu == "Graduate degree"] <- 6 

#Marital status
cd$marital[cd$marital ==  "Divorced"] <- 1
cd$marital[cd$marital == "Married"] <- 2
cd$marital[cd$marital == "Seperated"] <- 3
cd$marital[cd$marital == "Widowed"] <- 4

#changing up the variables for incomeRatio and trail conditions
#1. non white share/whiteShare: of white(or non-white) / total employee.
cd$nonwhite_share <- ((as.numeric(cd$nNonWhiteTrial))/25)*100
cd$white_share <- ((as.numeric(cd$nWhiteTrial))/25)*100

variations <- read.csv("C:/Users/ramat/Desktop/variations.csv", sep = ";")

#creating variations for non whites
cd$nw_variations[(cd$incomeRatio == 1) & (cd$trial_condition == 1)] <- 5
cd$nw_variations[cd$incomeRatio == "2" & cd$trial_condition =="1"] <- 6
cd$nw_variations[cd$incomeRatio == "3" & cd$trial_condition =="1"] <- 7
cd$nw_variations[cd$incomeRatio == "4" & cd$trial_condition =="1"] <- 8
cd$nw_variations[cd$incomeRatio == "5" & cd$trial_condition =="1"] <- 9
cd$nw_variations[cd$incomeRatio == "6" & cd$trial_condition =="1"] <- 10
cd$nw_variations[cd$incomeRatio == "7" & cd$trial_condition =="1"] <- 11

cd$nw_variations[cd$incomeRatio == "1" & cd$trial_condition =="2"] <- 10
cd$nw_variations[cd$incomeRatio == "2" & cd$trial_condition =="2"] <- 12
cd$nw_variations[cd$incomeRatio == "3" & cd$trial_condition =="2"] <- 14
cd$nw_variations[cd$incomeRatio == "4" & cd$trial_condition =="2"] <- 16
cd$nw_variations[cd$incomeRatio == "5" & cd$trial_condition =="2"] <- 18
cd$nw_variations[cd$incomeRatio == "6" & cd$trial_condition =="2"] <- 20
cd$nw_variations[cd$incomeRatio == "7" & cd$trial_condition =="2"] <- 22

cd$nw_variations[cd$incomeRatio == "1" & cd$trial_condition =="3"] <- 15
cd$nw_variations[cd$incomeRatio == "2" & cd$trial_condition =="3"] <- 18
cd$nw_variations[cd$incomeRatio == "3" & cd$trial_condition =="3"] <- 21
cd$nw_variations[cd$incomeRatio == "4" & cd$trial_condition =="3"] <- 24
cd$nw_variations[cd$incomeRatio == "5" & cd$trial_condition =="3"] <- 27
cd$nw_variations[cd$incomeRatio == "6" & cd$trial_condition =="3"] <- 30
cd$nw_variations[cd$incomeRatio == "7" & cd$trial_condition =="3"] <- 33

cd$nw_variations[cd$incomeRatio == "1" & cd$trial_condition =="4"] <- 20
cd$nw_variations[cd$incomeRatio == "2" & cd$trial_condition =="4"] <- 24
cd$nw_variations[cd$incomeRatio == "3" & cd$trial_condition =="4"] <- 28
cd$nw_variations[cd$incomeRatio == "4" & cd$trial_condition =="4"] <- 32
cd$nw_variations[cd$incomeRatio == "5" & cd$trial_condition =="4"] <- 36
cd$nw_variations[cd$incomeRatio == "6" & cd$trial_condition =="4"] <- 40
cd$nw_variations[cd$incomeRatio == "7" & cd$trial_condition =="4"] <- 44


cd$nw_variations[cd$incomeRatio == "1" & cd$trial_condition =="5"] <- 25
cd$nw_variations[cd$incomeRatio == "2" & cd$trial_condition =="5"] <- 30
cd$nw_variations[cd$incomeRatio == "3" & cd$trial_condition =="5"] <- 35
cd$nw_variations[cd$incomeRatio == "4" & cd$trial_condition =="5"] <- 40
cd$nw_variations[cd$incomeRatio == "5" & cd$trial_condition =="5"] <- 45
cd$nw_variations[cd$incomeRatio == "6" & cd$trial_condition =="5"] <- 50
cd$nw_variations[cd$incomeRatio == "7" & cd$trial_condition =="5"] <- 55

#Example for the code: the total income share of white (or non-white) employees / whiteShare (or non-white). E.g. trial_condition = 5, we have 10 white and 15 non-white employee -> nonwhite_share = 40%. and in income_ratio = 4, nwhite employees hold 40% of income share (600k/ 1.5m). Then, we will have 40%/40% = 1.
#creating variations for white 
cd$w_variations<- 100-cd$nw_variations
  
#Creating the income Shares in general for NW 
cd$incomeShare_NW<- (cd$nw_variations)/cd$nonwhite_share
round(cd$incomeShare_NW, digits=2)
#Creating the income shares in general for W
cd$incomeShare_W<- (cd$w_variations)/cd$white_share
round(cd$incomeShare_W,digits=2)

#For all variations(income) = 4 this number should be 1. for variations (income) < 4 should be larger than 1, and for trial_condition > 4 should be less than 1.

#numeric team_work
cd$team_work<-as.numeric(cd$team_work)
cd$work_in_team<-as.numeric(cd$work_in_team)
#just participants
X = cd[!duplicated(cd[ , c("subject")]),] #we have 97 final participants

```
```{R}

#create factors 
#cd$incomeShare_NW = as.factor(cd$incomeShare_NW)
#cd$incomeShare_W = as.factor(cd$incomeShare_W)

#cd$incomeShare_NW = factor(cd$incomeShare_NW,levels=rev(levels(cd$incomeShare_NW)))

#cd$incomeShare_W = factor(cd$incomeShare_W, levels=rev(levels(cd$incomeShare_W)))

#cd$edu = as.numeric(cd$edu)

```
```{R}
## summary:cond: white-more; nwmore; equal but for each variation (5)

#condition: 1-7
cd$Maj_income_share <- cd$incomeRatio
cd$Maj_income_share
cd$Maj_income_share[cd$Maj_income_share == "1" ] <- 75
cd$Maj_income_share[cd$Maj_income_share == "2" ] <- 70
cd$Maj_income_share[cd$Maj_income_share == "3" ] <- 65
cd$Maj_income_share[cd$Maj_income_share == "4" ] <- 60
cd$Maj_income_share[cd$Maj_income_share == "5" ] <- 65
cd$Maj_income_share[cd$Maj_income_share == "6" ] <- 70
cd$Maj_income_share[cd$Maj_income_share == "7" ] <- 75

cd$Majority <- cd$incomeRatio
cd$Maj_income_share[cd$Maj_income_share == "1" ] <- "W"
cd$Maj_income_share[cd$Maj_income_share == "2" ] <- "W"
cd$Maj_income_share[cd$Maj_income_share == "3" ] <- "W"
cd$Maj_income_share[cd$Maj_income_share == "4" ] <- "E"
cd$Maj_income_share[cd$Maj_income_share == "5" ] <- "NW"
cd$Maj_income_share[cd$Maj_income_share == "6" ] <- "NW"
cd$Maj_income_share[cd$Maj_income_share == "7" ] <- "NW"

# Main Effects Analysis

m1 <- lme4::glmer(fairness ~ nonwhite_share*Maj_income_share*Majority + (1 | X), cd, family = binomial(link = "logit"))
summary(m1)


#######################################################
########################################################

m2 <- lme4::glmer(team_work ~ incomeShare_NW + (1 | X), cd, family = binomial(link = "logit"))
summary(m2)

m3 <- lme4::glmer(work_in_team ~ incomeShare_NW + (1 | X), cd, family = binomial(link = "logit"))
summary(m3)

m4 <- lme4::glmer(distrust ~ incomeShare_NW + (1 | X), cd, family = binomial(link = "logit"))
summary(m4)

summary(m1)
summary(m2)
summary(m3)
summary(m4)

# subset
nw_maj <- subset(cd, incomeShare_NW>1)
w_min <- subset(cd, incomeShare_W<1)
nw_min <- subset(cd, incomeShare_NW<1)
equal <- subset(cd, incomeShare_NW==1)



#nw_maj$incomeShare_NW = factor(nw_maj$incomeShare_NW, levels=rev(levels(nw_maj$incomeShare_NW)))
#nw_maj<-as.matrix(nw_maj)

# Main Effects Analysis - minority has maj income
m5 <- lme4::glmer(fairness ~ incomeShare_NW + (1 | X), nw_maj, family = binomial(link = "logit"))
summary(m5)
#pos. effect incomeshare nw on fairness - not significant
# if income nw_maj rises the fairness rises  2.57

m6 <- lme4::glmer(team_work ~ incomeShare_NW+ (1 | X), nw_maj, family = binomial(link = "logit"))
summary(m6)
#not significant

m7 <- lme4::glmer(work_in_team ~ incomeShare_NW + (1 | X), nw_maj, family = binomial(link = "logit"))
summary(m7)
#not significant

m8 <- lme4::glmer(distrust ~ incomeShare_NW + (1 | X), nw_maj, family = binomial(link = "logit"))
summary(m8)
#not significant

# Main Effects Analysis - minority has min income
m9 <- lme4::glmer(fairness ~ incomeShare_NW * nw_min + (1 | X), nw_maj, family = binomial(link = "logit"))
summary(m9)
#add interaction! 
#compile all data


m10 <- lme4::glmer(team_work ~ incomeShare_NW+ (1 | X), nw_min, family = binomial(link = "logit"))
summary(m10)

m11 <- lme4::glmer(work_in_team ~ incomeShare_NW + (1 | X), nw_min, family = binomial(link = "logit"))
summary(m11)

m12 <- lme4::glmer(distrust ~ incomeShare_NW + (1 | X), nw_min, family = binomial(link = "logit"))
summary(m12)

#equal
m13 <- lme4::glmer(fairness ~ incomeShare_NW + (1 | X), equal, family = binomial(link = "logit"))
summary(m13)


######################## AFTER HOOMAN FEEDBACK####################

#create plot
reghelper::simple_slopes(m1)

fairness_maineffect <- interactions::interact_plot(m1, pred = cd$fairness, modx = cd$nonwhite_share, x.label = "income share held by majority", y.label = "0 = fair, 1 = unfair", legend.main = "majority held by...") + ylim(c(0,1))

fairness_maineffect_annotated <- annotate_figure(fairness_maineffect,
               top = text_grob("Fairness by Condition", color = "black", face = "bold", size = 14)) 
ggsave(plot = fairness_maineffect_annotated, width = 8, height = 6, filename = "fairness_maineffect.jpg")


#create html

htmlreg(l = list(m1, m2, m3, m4), center = TRUE, stars = c(0.001, 0.01, 0.05),
        bold = 0.05, caption = 'M1 = Fairness (DV), M2 = Teamwork (DV), M3 = Want to work in team (DV), M4 = Trust org (DV)',
        caption.above = TRUE, digits = 3, leading.zero = F)

###############################################################################
#idea: regress them once for each DV?
#example:
#Fairness ~ white/non-white ratio (5 values) * income_ratio + control variables 
#or maybe two options, would be good. (maj and equal, min)
#would be good to plot them next to each other. 

##summarise majority and minority
## to do: check reliabilites for each scale

```